id: AAE0303B8
title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the Profound
  Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
type: translation
pechas:
- IFAA668A2
- I3067A2CC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:25.343371
  last_modified_at: 2023-01-04 12:33:25.343381
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IFAA668A2/4B8D: 93A3
  I3067A2CC/1060: 93A3
